apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    meta.helm.sh/release-name: my-streama
    meta.helm.sh/release-namespace: mpizarro-dev
  labels:
    app.kubernetes.io/instance: my-streama
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: streama
    app.kubernetes.io/version: 1.10.4
    helm.sh/chart: streama-1.0.1
  name: my-streama
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Percent
        value: 20
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 30
        type: Pods
        value: 2
      selectPolicy: Max
      stabilizationWindowSeconds: 120
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageValue: "1"
        type: AverageValue
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-streama
