apiVersion: v1
data:
  mysql-password: c3RyZWFtYQ==
  mysql-root-password: VDVIaU11V2hpNg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-streama
    meta.helm.sh/release-namespace: mpizarro-dev
  labels:
    app.kubernetes.io/instance: my-streama
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.8.26
  name: my-streama-mysql
type: Opaque
