apiVersion: v1
imagePullSecrets:
- name: streama-dockercfg-cjxsp
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: my-streama
    meta.helm.sh/release-namespace: mpizarro-dev
  labels:
    app.kubernetes.io/instance: my-streama
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: streama
    app.kubernetes.io/version: 1.10.4
    helm.sh/chart: streama-1.0.1
  name: streama
secrets:
- name: streama-dockercfg-cjxsp
